### ISSUE TITLE
this api is TOO slim

### ISSUE THREAD

**Issue by j6k4m8** [coreylowman/slimnn#1]
https://github.com/coreylowman/slimnn/blob/968851d736a8786b5bf77e3f533bf509d8e09761/examples/simple.rs#L1

**Comment by j6k4m8** [comment]
jk dude — amazing work in this ecosystem, I love it!! gradually switching some of my ML workloads over to dfdx, can't wait to see what slimnn is like :)

**Comment by chelsea0x3b** [comment]
lmao ❤️
